let PokemonModel = [
    {
       "_id":1,
       "Image":"1.png",
       "Name":"Charizard",
       "Data":{
          "Position":"001",
          "Level":100,
          "Type":"Fire",
          "Ability":"Flames",
          "Height":1.7,
          "Weight":90.5
       }
    },
    {
       "_id":2,
       "Image":"2.png",
       "Name":"Squirtle",
       "Data":{
          "Position":"002",
          "Level":60,
          "Type":"Wates",
          "Ability":"Rain Dish",
          "Height":0.5,
          "Weight":9.0
       }
    },
    {
       "_id":3,
       "Image":"3.png",
       "Name":"Bulbaaur",
       "Data":{
          "Position":"003",
          "Level":52,
          "Type":"Grass",
          "Ability":"Overgrow",
          "Height":0.5,
          "Weight":9.0
       }
    },
    {
       "_id":4,
       "Image":"4.png",
       "Name":"Butterfree",
       "Data":{
          "Position":"004",
          "Level":120,
          "Type":"Fliying",
          "Ability":"Compound Eyes",
          "Height":0.5,
          "Weight":9.0
       }
    },
    {
       "_id":5,
       "Image":"5.png",
       "Name":"Pidgeot",
       "Data":{
          "Position":"005",
          "Level":45,
          "Type":"Fliying",
          "Ability":"Keen Eye",
          "Height":0.5,
          "Weight":9.0
       }
    },
    {
       "_id":6,
       "Image":"6.png",
       "Name":"Arbok",
       "Data":{
          "Position":"006",
          "Level":85,
          "Type":"Poison",
          "Ability":"Intimidate",
          "Height":0.5,
          "Weight":9.0
       }
    },
    {
       "_id":7,
       "Image":"7.png",
       "Name":"PiKachu",
       "Data":{
          "Position":"007",
          "Level":160,
          "Type":"Electric",
          "Ability":"Lightning Rod",
          "Height":0.5,
          "Weight":9.0
       }
    },
    {
       "_id":8,
       "Image":"8.png",
       "Name":"Raichu",
       "Data":{
          "Position":"008",
          "Level":160,
          "Type":"Electric",
          "Ability":"Static",
          "Height":0.5,
          "Weight":9.0
       }
    }
 ];